label afternoon2:
    "Class soon ends and it's time to head back to your room."
    scene bg riley-dorm with fade
    "You immediately start your homework. Thankfully it doesn't take long."
    "When you're done you stretch and look about your room. Not much going on here."
    "You decide that, instead of being a hermit, you'll go down to the common room."
    scene bg common-room with fade
    "As you enter the room you're immediately hit with the smell of acetone. You look over to see Ochako sitting on a couch painting her nails."
    "Todoroki, Bakugo, and Deku talk loudly while setting up a board game. Meanwhile Iida, despite everything, sits at a table desperately trying to study."
    menu:
        "Hangout with someone in the common room.":
            menu:
                "Sit with Ochako.":
                    call afternoon2nails
                "Talk to Iida.":
                    call afternoon2study
                "Go join the board game.":
                    call afternoon2game
        "Get some fresh air.":
            call afternoon2cat
    # call screen afternoon2

    label afternoon2game:
        $ izukupoints += 1
        $ shotopoints += 1
        $ katsukipoints += 1
        show katsuki at centerleft
        show izuku at center
        show shoto at centerright
        with dissolve
        riley "Hey guys what'cha doing?"
        izuku "We're setting up to play a board game, wanna join us?"
        riley "Sure!"
        if beatBakugo:
            katsuki "Good, now I'll have a worthy opponent. Get ready Riley, this time I'm gonna crush you into the ground!"
            riley "Bring it on!"
        else:
            katsuki "Good, another opponent for me to crush!"
            riley "We'll see about that!"
        "The game starts and quickly gets heated."
        katsuki "You bastard, you stole my longest road!"
        riley "I'll literally do anything for a sheep!"
        shoto "I swear if I don't get some wheat soon I'm going to burn these fields to ashes!"
        izuku "Calm down you guys!"
        "But Deku's pleas go unheard."
        "In the end the pieces are scattered, the board half burned, and the four of you end up dragged to your classroom to explain to Aizawa why the fire alarm went off."
        scene bg front-of-classroom with fade
        show katsuki at centerleft
        show izuku at center
        show shoto at centerright
        with dissolve
        aizawa "Someone start explaining..."
        izuku "Well-"
        aizawa "and it better be a good reason."
        katsuki "..."
        shoto "..."
        izuku "..."
        riley "..."
        aizawa "Well?"
        "You decide to speak up before Aizawa gets any more mad."
        riley "There's not a good reason, we just got carried away and Todoroki's fire set off the alarm... and the sprinklers..."
        "Aizawa sighs"
        aizawa "I appreciate your honesty Riley and for that I'll let it slide THIS TIME but I want you all to sit here and think about what you've done."
        aizawa "And if it happens again I'll see you all expelled."
        "With that he turns to leave (and probably deal with the fire department)."
        "You all sit quietly left alone in the classroom. When Aizawa finally lets you go you all shuffle out of the classroom and start your walk back to the dorms."
        "Shoto looks ashamed, Bakugo annoyed, and Deku like he's about to cry."
        "You're the first to break the silence."
        riley "Deku was right, we should've settled down... sorry we got you in trouble too Deku."
        "Shoto nods."
        shoto "Sorry."
        katsuki "Tch..."
        "He looks away."
        katsuki "Sorry I guess..."
        "Deku sniffs."
        izuku "It's okay you guys, but next time try to remember it's just a game..."
        riley "Yeah, we will."
        izuku "Okay, good."
        "He still looks on the verge of tears, but the tension between you has eased."
        "The four of you walk back in silence the rest of the way."
        "When you arrive you bid the other three goodnight and head to your room."
    return

    label afternoon2study:
        $ tenyapoints += 1
        show tenya at center with dissolve
        "Iida looks up as you approach"
        tenya "Good afternoon Riley."
        riley "Hey Iida. What'cha up to?"
        tenya "Well, I thought it would be good for me to get out of my room for a while, but I find it exceedingly difficult to study given the current conditions."
        "Bakugo suddenly stands up and lets out a string of curses, he's obviously not winning."
        "Iida sighs."
        riley "I guess that is a problem..."
        riley "Well I guess we could ask them to quiet down, but it's as much their space as it is ours so..."
        "Iida nods."
        riley "Ah! I know! It's not the most conventional place, but we can study in the kitchen. It'll be a lot quieter than here for sure."
        tenya "Hmm, I suppose that could work. Let's try it!"
        "You and Iida move his study materials to the kitchen table and you pull out your textbook."
        "After studying for a few minutes Iida looks up from his notebook."
        tenya "You're right Riley, this is unconvential, but much more conducive to studying."
        "You simply smile in response and he smiles back, then both of you go back to studying."
        "After a couple of hours Iida closes his notebook and turns to you."
        tenya "I think that's enough studying for today."
        "He looks at his watch."
        tenya "Besides, it's just about dinner time."
        riley "Yeah, I'm getting hungry."
        tenya "What are you going to make yourself for dinner Riley?"
        riley "Probably frozen pizza, ehehe..."
        tenya "Do you not know how to cook?"
        "You shake your head."
        tenya "In that case, why don't we cook together! In fact, why don't we treat the whole dorm!"
        riley "Sure, that sounds like fun!"
        tenya "Now let's see what ingredients we have."
        "Iida walks over to the fridge and looks inside."
        tenya "The only meat we have is beef, but we have plenty of vegetables..."
        tenya "I know! We'll make beef stew!"
        riley "Sounds great! Where do we start?"
        "You proceed to make a veritable vat of delicious beef stew, while under Iida's careful supervision of course."
        "Before you can even sound the metaphorical dinner bell you realize a few of your classmates have already begun to stream into the kitchen, obviously lured by the smell of food."
        tenya "Come fellow students! We made enough for everyone!"
        "The two of you serve several of your classmates before sitting down to eat yourselves."
        riley "This is delicious, even if I do say so myself!"
        tenya "I agree!"
        eijiro "Yeah, this is great!"
        shoto "Thanks."
        ochako "Yeah, thanks you two!"
        momo "Thank you for the meal!"
        izuku "Where did you guys learn to cook like this?"
        riley "Actually this is my first time cooking anything more complicated than toast..."
        tenya "Yes, but Riley is a natural!"
        "The stew was a hit! A few of your classmates even ask for seconds. By the time everyone has eaten the pot is basically empty."
        "When you and Iida finally finish cleaning he smiles at you."
        tenya "I'd say that's a job well done. We'll have to do this again sometime."
        riley "Yeah, it was alot of fun."
        tenya "For now though I think we'd best get to sleep. Goodnight Riley."
        riley "Goodnight."
        "And with that he leaves the kitchen and heads upstairs to his room. You soon do the same."
    return

    label afternoon2nails:
        $ ochakopoints += 1
        show ochako at center
        "You carefully sit down next to Ochako."
        "She speaks without looking up."
        ochako "Hey Riley."
        riley "Hi Ochako. Are you painting your nails for a special occasion or just because?"
        ochako "Just because, wanna join me?"
        riley "Sure, why not."
        "She slides over a bag full of different nail polishes with her unpainted hand."
        ochako "Here, use whatever color you like."
        riley "Hmm I think I'll use this light blue one."
        ochako "Ooh, good choice."
        "She finishes much sooner than you and with much better results."
        riley "Mine don't look so great..."
        ochako "That's okay, that's why we have this!"
        "She pulls a nail polish remover pen out of her bag with a flourish."
        "She helps you fix your smudges and other little imperfections."
        ochako "There, now you could never tell they were messy in the first place!"
        riley "Nice!"
        "You continue to chat while your nails dry."
        if ochakoMall:
            ochako "Now we'll have nice nails for our mall trip this weekend!"
            ochako "Assuming we can manage to not chip them that long hehe"
            riley "Hopefully!"
            riley "Do you have anything particular to do at the mall by the way or just going for fun?"
            ochako "Well I figure we'll do some shopping and grab lunch, but otherwise I don't really have a plan."
            ochako "Deku and Todoroki are coming too by the way. I invited some others, but most already had plans and Bakugo just blew me off..."
            riley "Cool, I'm looking forward to it!"
        else:
            ochako "Oh I've been meaning to ask you something! Me, Deku, and Todoroki are gonna hang out at the mall this weekend you wanna come with?"
            menu:
                "Sure!":
                    ochako "Great, this is gonna be so much fun! We'll go shopping and grab some lunch! It'll be great!"
                    riley "Cool, I'm looking forward to it."
                "Sorry, I have plans.":
                    ochako "Aww, too bad. Maybe next time?"
                    riley "Yeah, next time."
        ochako "There! They should be dry now. Next up, makeup!"
        riley "Ehh I don't really do makeup."
        ochako "Oh, hmm... I know! You can do MY makeup!"
        riley "Ehh are you sure?"
        ochako "Yeah I've always wanted someone else to do my makeup and see if it looks any different."
        riley "Okay, I'll do my best then!"
        ochako "Thank you!"
        "You spend the next 30 minutes doing Ochako's makeup."
        riley "There, done!"
        "You hand Ochako the mirror and her eyes go wide."
        ochako "..."
        ochako "pfft..."
        ochako "HAHAHAHAHAHA!"
        "She laughs for a good minute and a half."
        ochako "Omigod Riley what did you do to my face?"
        "She looks in the mirror, snorts, and immediately bursts out laughing again."
        "By this time some of the others in the room have come over to see what the commotion is about."
        show izuku at centerright
        show shoto at centerleft
        show katsuki at leftoffset
        with dissolve
        izuku "What's so funny Ocha..."
        "He catches a glimpse of her face."
        izuku "ko..."
        "He stifles a laugh."
        izuku "Uhh Ochako your makeup..."
        ochako "I KNOW RIGHT?"
        "Deku lets out his laugh in full now, and her face even gets a chuckle out of Todoroki."
        riley "To be fair I did tell you I don't really do makeup!"
        ochako "Riley you went above and beyond bad, this is something truly spectacularly awful!"
        "She looks in the mirror and laughs again."
        riley "Sorry, sorry."
        ochako "It's fine. Help me wipe this off before the whole dorm sees."
        "Bakugo quickly snaps a picture with his phone."
        ochako "DON'T YOU DARE!"
        "She jumps up to try to snatch the phone away but Bakugo is one step ahead of her. The two of them do laps around the couch. Playing keep away."
        ochako "Riley, you did this to me at least help me catch him!"
        katsuki "C'mon Riley, it's funny! It won't kill her for our classmates to see!"
        menu:
            "Help Ochako.":
                $ ochakopoints += 1
                "With the two of you working together you manage to tackle Bakugo and pin him down."
                "Ochako snatches the phone away and quickly deletes the picture. She then drops the phone unceremoniously next to him."
                ochako "Try that again and I'll kill you!"
                katsuki "Tch... whatever."
                ochako "You may release him now Riley."
                "You let Bakugo go and stand up."
                ochako "Now help me get to a sink without anyone else seeing please!"
                "You drape your jacket over her head and lead her to the kitchen sink."
                "She quickly washes your wonderfully hideous creation away down the drain."
                ochako "Thanks Riley, that was good for a laugh."
                "She looks out the window."
                ochako "Wow it got late fast... I should probably go finish my homework then get to bed."
                riley "Yeah I should get to bed too."
                ochako "Well it was fun Riley, talk to you tomorrow!"
                riley "Goodnight!"
            "Help Bakugo.":
                $ katsukipoints += 1
                "You restrain Ochako (with much difficulty) as Bakugo sends the text to the entire class."
                katsuki "Okay, done. You can let her go now."
                "You release Ochako."
                ochako "Ugh! You two are the worst!"
                katsuki "Hey, it's not that bad, everyone'll get a laugh and then it'll be over."
                ochako "Yeah, get a laugh AT MY EXPENSE, jerks."
                ochako "Ugh, I need to go wash this off, not that it really matters now..."
                "She storms off."
                katsuki "Ehh, she'll get over it. Thanks Riley."
                riley "No problem!"
                katsuki "Anyway, I should get to bed. Later."
                riley "Night."
    return

    label afternoon2cat:
        $ hitoshipoints += 1
        $ shinsoCat = True
        "You leave the common room and are greeted by a fresh breeze, much nicer than chemical smell inside."
        "Since you didn't have anywhere specific in mind, you pick a random direction and start walking."
        "You end up at a park and see familiar a shock of indigo hair sticking out from behind a bush."
        riley "Shinso?"
        hitoshi "Shhh."
        "You walk over and see why he shushed you. A stray cat stands in front of him about 3 feet away. You squat down with him."
        "He smiles and holds out his hand and the cat stands stock still. Then, ever so slowly, moves a step forward. Then another, and another."
        "Soon the cat is softly headbutting Shinso's hand. Shinso smiles."
        hitoshi "There you go, buddy."
        "He squats there petting it for a minute before the cat decides to investigate you. You slowly move your hand to pet it and it purrs."
        hitoshi "I think he likes you. Try picking him up."
        riley "Uhh, okay."
        "You carefully reach forward and try to pick up the cat and, to your surprise, it lets you."
        "Once the cat is securely cradled in your arms, you stand and Shinso joins you."
        riley "What now?"
        hitoshi "Well it doesn't have a collar... but it's too tame to have been a stray for long... someone must have just abandonned it here..."
        "He looks sort of angry, but just sighs."
        hitoshi "I guess we should probably get it inside first, poor guy looks cold."
        "He smiles at the cat again."
        riley "Uh I guess we could take it to the dorms... I think animals are allowed, I mean Koda has a rabbit so..."
        hitoshi "Okay, that sounds like a good idea."
        "The two of you walk back to the dorms, stopping only once to pick up some cat necessities from a groccery store along the way."
        "When you reach the front door Shinso stops."
        hitoshi "Well, bye I guess, take good care of him."
        riley "Err wait, I don't really know how to take care of a cat."
        hitoshi "Really? You seem like you've handled cats before."
        riley "Nope, never."
        hitoshi "Well I guess I should teach you the basics then. It's not that hard."
        riley "Yeah, come on lets go to my room."
        "He nods."
        hitoshi "Lead the way."
        "The two of you make it to your room without meeting anyone else."
        "You stop in front of the door."
        riley "Err... my keys are in my pocket, could you?..."
        "He gives you a look."
        hitoshi "How about I just hold the cat."
        riley "Oh yeah, that's a better idea."
        "He takes the cat from you and you retrieve your keys and open the door. You're silently thankful your room hasn't had much time to get messy."
        "Shinso walks in and you close the door behind him and he lets the cat jump to the floor. He immediately starts exploring his new surroundings. Shinso watches him with a smile."
        "A thought occurs to you."
        riley "We should probably name him."
        hitoshi "What?"
        riley "Well I figure if we're gonna have a pet he should probably have a name. We can't just keep calling him 'him'"
        hitoshi "Oh, you're planning on keeping him? I thought you were gonna take it to a shelter or something."
        riley "Well I guess I could but... I dunno that just feels wrong."
        hitoshi "Yeah it does, doesn't it?"
        "He looks towards the cat who is now rubbing against your legs and purring."
        hitoshi "Hmm... how about... Jiai?"
        riley "I like it! 'kindness' a good name for such a sweetheart!"
        "You pick up Jiai, and then look to Shinso who is smiling at you or maybe the cat, you can't really tell."
        riley "So teach me how to tak care of little Jiai."
        hitoshi "Oh, right."
        "Shinso gives you a basic primer on caring for and handling cats. You pay attention closely and learn all you can."
        riley "Okay, I think I got it."
        hitoshi "Okay, good. I guess I better go then, it's late."
        riley "Yeah, but come back and visit sometime."
        "He stops and looks a bit surprised."
        riley "Err, at least to see Jiai?"
        "You lift the cat sleeping in your arms just a bit."
        "He smiles."
        hitoshi "Okay, sure. See you soon Riley."
        riley "Good night Shinso."
    return
return
