label day3start:
    play music "audio/ill-become-a-hero.mp3" fadeout 2.0 fadein 2.0
    scene bg riley-dorm with fade
    "Once again, morning comes too soon."
    if shinsoCat:
        "You wake up to a hungry cat pawing at your face."
        riley "Five more minutes, please?"
        "But Jiai's pawing is relentless."
        riley "Okay, okay I'm up."
        "You look at the time once you're done emptying the can of food into the bowl. An hour before class starts, your alarm suddenly goes off."
        "You sigh and shut it off."
        riley "I guess I might as well get ready, thanks for the early wake up call Jiai... Jiai apologizes by continuing to scarf down his food."
        "You head to the bathroom and wash up, passing a few of your classmates on the way. You quickly brush your teeth and return to your room."
        "You change into your uniform and turn to Jiai."
        riley "You be good while I'm gone, Jiai."
        "Jiai looks at you questioningly. You pet him and then turn to leave."
        menu:
            "Get some breakfast.":
                $ ochakopoints += 1
                $ izukupoints += 1
                "You walk into the dorm kitchen and are greeted by various smells from previous occupants."
                "Currently though only Ochako and Deku are here cooking and chatting."
                "Ochako turns to you as you enter."
                ochako "Morning Riley!"
                riley "Morning."
                izuku "We're almost done here, there should be enough for three if you want to join us."
                riley "Sure, sounds great!"
                "You busy yourself getting plates and utensils for the three of you and soon Deku and Ochako are bringing over a pan full of eggs and bacon and a plate of toast."
                riley "Wow you guys worked hard, thanks for sharing with me!"
                ochako "No problem, the more the merrier!"
                izuku "We were kind of hoping you, Iida, and Todoroki would show up so we made plenty."
                riley "Wow that's really nice of you guys!"
                "They both beam at you."
                "The three of you eat and chit chat and then, after washing the dishes, walk to class together."
                "Class drags by but finally lunchtime arrives."
            "Hang out in the common room.":
                $ shotopoints += 1
                "You see Todoroki sitting alone in the common room. Reading once again."
                "You quietly sit down next to him."
                riley "Hey Todoroki."
                shoto "Hey Riley."
                "He marks his page, closes his book, and looks at you expectantly."
                if todorokiBook:
                    riley "You still working on that book from the other day?"
                    "He nods"
                    riley "Know what it's about yet?"
                    if shotopoints >= 3:
                        shoto "It's set around the time of the Fourth Crusade. It's main character is Alfred one of the Fair Folk living in the human world."
                        shoto "I think it's ultimately about Alfred, who is trying to come to terms with who he is and his powers, and Althea, who is is in love with him and trying to help him."
                        shoto "There's more to it than that but that's a decent summary I think."
                        "You listen intently until the end."
                        riley "Wow that sounds like a really interesting read!"
                        shoto "Yeah, it's pretty good so far."
                        "He gives you a small smile."
                        shoto "Sorry I know you just got here, but I've gotta get ready for class."
                        riley "Don't worry about it!"
                        "He nods, then stands and walks over to the stairs but then stops."
                        shoto "I should be done with by the end of today I think, so come see me soon."
                        "He doesn't wait for your response and walks swiftly up the stairs."
                        "You smile back at him nonetheless. Then, once he's gone, you pick up your schoolbag and head to class."
                        "Class drags by but finally lunchtime arrives."
                    else:
                        shoto "It's about the Fourth Crusade and Elves."
                        riley "Ahh, that sounds neat."
                        shoto "Sorry, I have to get ready for class."
                        riley "Oh sorry, don't let me keep you."
                        "He stands and walks up the stairs and out of view."
                        "Once he's gone you pick up your schoolbag and head to class."
                        "Class drags by but finally lunchtime arrives."
            "Go to class early.":
                "You decide to leave for class early."
                "You walk alone in the peaceful morning light for several minutes. Then a little ways off, down a path not leading towards class, you spot Shinso."
                riley "Shinso!"
                "He turns and waves, but then keeps walking."
                menu:
                    "Catch up with Shinso.":
                        $ hitoshipoints
                        "You speed up your pace to catch up with Shinso."
                        "He turns to you and raises and eyebrow."
                        hitoshi "Don't you have class?"
                        riley "I do, but it's early still! We can walk and talk for a while."
                        "He rubs his hand on his neck."
                        hitoshi "Okay."
                        "Hey I can't seem to get Jiai to sleep in his own bed. Any tips for that?"
                        if hitoshipoints >= 3:
                            hitoshi "I usually just let my cats sleep with me, so not really. I read that catnip or treats might work though."
                            riley "Hmm okay, maybe I'll just let him sleep in my bed. I just feel bad we wasted money on a cat bed..."
                            hitoshi "He'll probably still use it sometimes."
                            riley "Well that's good at least. So Shinso, you have cats at home yeah?"
                            hitoshi "Yeah, I have two cats right now. I'd have more but my parents wouldn't let me."
                            riley "Aww, Shinso is gonna grow up to be a little ol' cat hoarder!~"
                            hitoshi "I probably will."
                            "You were teasing, but he looks dead serious."
                            riley "Err... how many cats do you want exactly?"
                            hitoshi "I think about fifty is a good number."
                            riley "Fifty?!"
                            "He finally cracks a smile at your reaction."
                            hitoshi "I'm joking Riley."
                            riley "Oh..."
                            "He chuckles to himself."
                            hitoshi "Fifty is a bit much, even for me. Twenty is more reasonable, right?"
                            riley "Err... are you still joking?"
                            "He smiles."
                            hitoshi "Maybe."
                            "The two of you walk the rest of the way chatting and laughing."
                        else:
                            hitoshi "Not really, no."
                            riley "I guess I'll just have to let him sleep in my bed then."
                            "The two of you walk together, occasionally speaking when one of you comes up with something to say."
                        "Soon Shinso stops walking."
                        hitoshi "Well this is my class. Nice talking to you Riley."
                        riley "Oh I didn't realize I had walked this far with you. Err... Where are we anyway?"
                        hitoshi "The General Studies department."
                        riley "Uhh how far is that from the my class?"
                        hitoshi "Riley your class is on the other side of the campus..."
                        "You check your phone for the time. It's ten minutes until your class starts."
                        riley "Oh crap! GottagoShinsobye!"
                        "You book it towards your classroom."
                        "You open then door and sigh in relief."
                        riley "I made it..."
                        aizawa "Just barely."
                        "You jump at the voice behind you."
                        aizawa "Get to your seat Riley."
                        "You hurriedly walk over to your desk and sit down."
                        "Class drags by but finally lunchtime arrives."
                    "Go to class.":
                        "You wave back and continue on your way."
                        "When you get to class you see several students milling about. Bakugo is busy reading something and Iida has his notebook out and is writing."
                        menu:
                            "Talk to Bakugo.":
                                $ katsukipoints
                                $ bakugoBook = True
                                "You walk over to Bakugo and look over his shoulder at what he's reading."
                                riley "Is that manga?"
                                "He turns to face you."
                                katsuki "Obviously."
                                riley "What's it about?"
                                katsuki "Heros, duh."
                                riley "Hmm, so you're a nerd too huh?"
                                katsuki "Excuse me?"
                                "He looks mildly annoyed, but you decide t push your luck."
                                riley "Maybe even as much of a nerd as Deku."
                                katsuki "WHAT DID YOU JUST SAY?!"
                                "Sparks start popping off his hands, and without realizing it he's soon burned his own manga."
                                riley "Uhm, you just..."
                                "He looks down at his hands and now ruined manga."
                                katsuki "GAH! Dammit! Now I have to buy another one..."
                                riley "Sorry, Bakugo, I was just teasing."
                                katsuki "Whatever..."
                                "Before you can apologize further Aizawa walks in and orders everyone into their seats."
                                "Class drags by but finally lunchtime arrives."
                            "Sit with Iida":
                                $ tenyapoints
                                "Iida appears to be, once again, studying."
                                riley "What'cha studying now Iida?"
                                "He looks up from his notes."
                                tenya "I'm just reviewing yesterday's lesson."
                                riley "You sure study a lot, y'know?"
                                tenya "Studying is important."
                                riley "True enough, but so is relaxing."
                                tenya "Fair point."
                                "He pointedly closes his notebook and looks up at you."
                                tenya "So... um... how are you doing in your studies Riley?"
                                "You almost laugh at the topic he picked, but you answer him anyway."
                                riley "I'm doing pretty well, I understand the material we've covered so far but..."
                                "He tilts his head, and gestures for you to continue."
                                riley "Well catching up on what I missed at the beginning is a bit tough."
                                tenya "I could tutor you some time if you would like."
                                riley "Really? That'd be great!"
                                "He smiles proudly."
                                tenya "Alright, just let me know when."
                                riley "Thanks Iida."
                                "The two of you chat about studying and studying techniques until Aizawa walks in and you have to go to your seat."
                                "Class drags by but finally lunchtime arrives."
    else:
        "You decide to snooze your alarm. Just once you tell yourself...{w} Or Twice...{w} Three times can't hurt...{w} for real this time..."
        "An hour later you find yourself hurriedly changing into your school uniform and sprinting out the door."
        scene bg outside-classroom with fade
        "You stop to catch your breath outside the classroom."
        "You swallow hard and open the door."
        aizawa "Good of you to join us Riley."
        riley "S-sorry!"
        aizawa "Take your seat. Now."
        riley "Yes sir!"
        "You practically sprint over to your seat."
        "Despite your tardiness class goes on fairly smoothly and soon it's lunchtime."
